### ISSUE TITLE
Add rsync note to install section of readme or make a better error

### ISSUE THREAD

**Issue by mjarkk** [anoff/remote-code#10]
While i was trying to install this i noticed that rsync had a wired error.  
```
Error: rsync exited with code 127
```  
When i saw this error for the first time i though it was a problem with rsync but the problem was that it wasn't installed  
That error code looks a bit misleading, it would be nice if the error was something like:
```
Error: rsync not found 
```
Or add a note to install rsync to the install section of the README

**Comment by anoff** [comment]
Hey @mjarkk first, sorry for the late response, I was off grid over new years. Thanks for taking an interest in the project and letting me know about this issue!

Do you still have this issue and could you please provide some details e.g. is that happening on the client or the remote?

**Comment by mjarkk** [comment]
This happened on the host.  
After i installed rsync it didn't do this anymore.   

The host (my laptop)
- OS: Arch linux
- Shell: zsh
- `uname -r`: 4.20.0-arch1-1-ARCH
- Has installed: nodejs, yarn, npm, rsync
- `lsb_release -a`
```
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

**Comment by anoff** [comment]
Ah ok now I get what you mean! Thanks for the info will update the docs and see if I can add a step to check for prerequisites
